project_id = "jurzzgvupmgfffdodpmz"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-webhook.env]
TELEGRAM_BOT_TOKEN = "8222802213:AAE-n9hBawD5D6EaZ82nt3vFWq6CGKLiXho"

[functions.send-telegram-message]
verify_jwt = false

[functions.send-telegram-message.env]
TELEGRAM_BOT_TOKEN = "8222802213:AAE-n9hBawD5D6EaZ82nt3vFWq6CGKLiXho"
